// <auto-generated />
using System;
using GT.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GT.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(GtDbContext))]
    [Migration("20260812164125_Modulo6Facturacion")]
    partial class Modulo6Facturacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("NumeroDeViaje");

            modelBuilder.Entity("GT.Domain.Choferes.Chofer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("TransportistaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cuil")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("TransportistaId");

                    b.ToTable("Choferes", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Choferes.Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoNombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ArchivoRuta")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ArchivoTipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ChoferId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentacionTipoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentacionTipoId");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("ChoferId", "DocumentacionTipoId", "FechaVencimiento")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Documentaciones_ChoferId_TipoId_Vencimiento");

                    b.ToTable("Documentaciones", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Choferes.DocumentacionTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte>("Ambito")
                        .HasColumnType("tinyint");

                    b.Property<int>("DiasAvisoVencimiento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("DocumentacionTipos", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Choferes.Transportista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.ToTable("Transportistas", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Facturacion.CambioDeEstadoFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("EstadoAnterior")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("EstadoNuevo")
                        .HasColumnType("tinyint");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("FacturaId", "OcurridoEn");

                    b.ToTable("CambiosDeEstadoFactura", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Facturacion.EmpresaEmisora", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Cbu")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("CondicionIva")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("IngresosBrutos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("InicioActividades")
                        .HasColumnType("date");

                    b.Property<string>("LogoNombreOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LogoRuta")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("LogoTipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PuntoDeVenta")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EmpresaEmisora", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmpresaEmisora_FilaUnica", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("GT.Domain.Facturacion.FacturaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cae")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("CaeVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("ClienteCuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ClienteDomicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteRazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("CondicionDeVenta")
                        .HasColumnType("tinyint");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentoRuta")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("EmisorCbu")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("EmisorCondicionIva")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmisorCuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("EmisorDomicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmisorEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmisorIngresosBrutos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("EmisorInicioActividades")
                        .HasColumnType("date");

                    b.Property<string>("EmisorPuntoDeVenta")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("EmisorRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmisorTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FacturaReemplazadaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaCobro")
                        .HasColumnType("date");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Neto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<short>("PeriodoAnio")
                        .HasColumnType("smallint");

                    b.Property<byte>("PeriodoMes")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TipoComprobante")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TipoFacturacion")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("VencimientoPago")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Facturas_ClienteId");

                    b.HasIndex("FacturaReemplazadaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Facturas_FacturaReemplazada")
                        .HasFilter("[FacturaReemplazadaId] IS NOT NULL");

                    b.HasIndex("NumeroComprobante")
                        .IsUnique()
                        .HasDatabaseName("IX_Facturas_Numero")
                        .HasFilter("[Estado] <> 2");

                    b.HasIndex("Estado", "VencimientoPago")
                        .HasDatabaseName("IX_Facturas_Estado_VencimientoPago");

                    b.HasIndex("Fecha", "NumeroComprobante")
                        .IsDescending()
                        .HasDatabaseName("IX_Facturas_Fecha_Numero");

                    b.ToTable("Facturas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Facturas_PeriodoMes", "[PeriodoMes] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_Facturas_Total", "[Total] = [Neto] + [Iva]");
                        });
                });

            modelBuilder.Entity("GT.Domain.Flota.DocumentacionVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoNombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ArchivoRuta")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ArchivoTipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentacionTipoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentacionTipoId");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("VehiculoId", "DocumentacionTipoId", "FechaVencimiento")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_DocumentacionesVehiculo_VehiculoId_TipoId_Vencimiento");

                    b.ToTable("DocumentacionesVehiculo", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Flota.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposVehiculo", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Flota.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte>("EstadoOperativo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("TransportistaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.HasIndex("TipoVehiculoId");

                    b.HasIndex("TransportistaId");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Personas.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Usuarios.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Usuarios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PasswordActualizadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PasswordTemporalGeneradaEn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsernameNormalizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasFilter("[PersonaId] IS NOT NULL");

                    b.HasIndex("UsernameNormalizado")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Viajes.CambioDeEstadoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("EstadoAnterior")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EstadoNuevo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ViajeId", "OcurridoEn");

                    b.ToTable("CambiosDeEstadoViaje", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Viajes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Viajes.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChoferId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetalleCarga")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.NumeroDeViaje");

                    b.Property<string>("NumeroRemito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TransportistaId")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoferId")
                        .IsUnique()
                        .HasDatabaseName("IX_Viajes_ChoferEnCurso")
                        .HasFilter("[ChoferId] IS NOT NULL AND [Estado] = 1");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FacturaId")
                        .HasDatabaseName("IX_Viajes_FacturaId");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Viajes_Numero");

                    b.HasIndex("NumeroRemito")
                        .IsUnique()
                        .HasDatabaseName("IX_Viajes_NumeroRemito")
                        .HasFilter("[NumeroRemito] IS NOT NULL AND [Estado] <> 3");

                    b.HasIndex("TransportistaId");

                    b.HasIndex("VehiculoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Viajes_VehiculoEnCurso")
                        .HasFilter("[VehiculoId] IS NOT NULL AND [Estado] = 1");

                    b.HasIndex("Fecha", "Numero")
                        .IsDescending()
                        .HasDatabaseName("IX_Viajes_Fecha_Numero");

                    b.ToTable("Viajes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Viajes_Importe", "[Importe] >= 0");
                        });
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("PermisosId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("PermisosId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("GT.Domain.Choferes.Chofer", b =>
                {
                    b.HasOne("GT.Domain.Personas.Persona", "Persona")
                        .WithOne("Chofer")
                        .HasForeignKey("GT.Domain.Choferes.Chofer", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Choferes.Transportista", "Transportista")
                        .WithMany("Choferes")
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("GT.Domain.Choferes.Documentacion", b =>
                {
                    b.HasOne("GT.Domain.Choferes.Chofer", "Chofer")
                        .WithMany("Documentacion")
                        .HasForeignKey("ChoferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Choferes.DocumentacionTipo", "Tipo")
                        .WithMany("Documentos")
                        .HasForeignKey("DocumentacionTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("GT.Domain.Facturacion.CambioDeEstadoFactura", b =>
                {
                    b.HasOne("GT.Domain.Facturacion.FacturaCliente", "Factura")
                        .WithMany("CambiosDeEstado")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GT.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GT.Domain.Facturacion.FacturaCliente", b =>
                {
                    b.HasOne("GT.Domain.Viajes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Facturacion.FacturaCliente", "FacturaReemplazada")
                        .WithMany()
                        .HasForeignKey("FacturaReemplazadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("FacturaReemplazada");
                });

            modelBuilder.Entity("GT.Domain.Flota.DocumentacionVehiculo", b =>
                {
                    b.HasOne("GT.Domain.Choferes.DocumentacionTipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("DocumentacionTipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Flota.Vehiculo", "Vehiculo")
                        .WithMany("Documentacion")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("GT.Domain.Flota.Vehiculo", b =>
                {
                    b.HasOne("GT.Domain.Flota.TipoVehiculo", "Tipo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Choferes.Transportista", "Transportista")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("GT.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("GT.Domain.Personas.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("GT.Domain.Usuarios.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("GT.Domain.Viajes.CambioDeEstadoViaje", b =>
                {
                    b.HasOne("GT.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Viajes.Viaje", "Viaje")
                        .WithMany("CambiosDeEstado")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("GT.Domain.Viajes.Viaje", b =>
                {
                    b.HasOne("GT.Domain.Choferes.Chofer", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GT.Domain.Viajes.Cliente", "Cliente")
                        .WithMany("Viajes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GT.Domain.Facturacion.FacturaCliente", "Factura")
                        .WithMany("Viajes")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GT.Domain.Choferes.Transportista", "Transportista")
                        .WithMany()
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GT.Domain.Flota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chofer");

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("Transportista");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("GT.Domain.Usuarios.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GT.Domain.Usuarios.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("GT.Domain.Usuarios.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GT.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GT.Domain.Choferes.Chofer", b =>
                {
                    b.Navigation("Documentacion");
                });

            modelBuilder.Entity("GT.Domain.Choferes.DocumentacionTipo", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("GT.Domain.Choferes.Transportista", b =>
                {
                    b.Navigation("Choferes");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("GT.Domain.Facturacion.FacturaCliente", b =>
                {
                    b.Navigation("CambiosDeEstado");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("GT.Domain.Flota.TipoVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("GT.Domain.Flota.Vehiculo", b =>
                {
                    b.Navigation("Documentacion");
                });

            modelBuilder.Entity("GT.Domain.Personas.Persona", b =>
                {
                    b.Navigation("Chofer");
                });

            modelBuilder.Entity("GT.Domain.Viajes.Cliente", b =>
                {
                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("GT.Domain.Viajes.Viaje", b =>
                {
                    b.Navigation("CambiosDeEstado");
                });
#pragma warning restore 612, 618
        }
    }
}
